// <auto-generated />
using System;
using ClinicPass.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicPass.Migrations
{
    [DbContext(typeof(ClinicPassContext))]
    [Migration("20251206180123_CambiosTemporalesFichaSeguimiento")]
    partial class CambiosTemporalesFichaSeguimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.CoberturaMedica", b =>
                {
                    b.Property<int>("IdCobertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCobertura"));

                    b.Property<string>("NombreCobertura")
                        .HasColumnType("text");

                    b.Property<string>("TipoCobertura")
                        .HasColumnType("text");

                    b.HasKey("IdCobertura");

                    b.ToTable("CoberturasMedicas");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumento"));

                    b.Property<int>("FichaSeguimientoIdFichaSeguimiento")
                        .HasColumnType("integer");

                    b.Property<int>("IdFichaSeguimiento")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Ruta")
                        .HasColumnType("text");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.HasKey("IdDocumento");

                    b.HasIndex("FichaSeguimientoIdFichaSeguimiento");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", b =>
                {
                    b.Property<int>("IdFichaSeguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFichaSeguimiento"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HistoriaClinicaIdHistorialClinico")
                        .HasColumnType("integer");

                    b.Property<int?>("HistorialClinicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("ProfesionalIdUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("IdFichaSeguimiento");

                    b.HasIndex("HistoriaClinicaIdHistorialClinico");

                    b.HasIndex("ProfesionalIdUsuario");

                    b.ToTable("FichasDeSeguimiento");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HCTratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .HasColumnType("integer");

                    b.Property<int>("IdHistorialClinico")
                        .HasColumnType("integer");

                    b.Property<int>("HistoriaClinicaIdHistorialClinico")
                        .HasColumnType("integer");

                    b.Property<int>("TratamientoIdTratamiento")
                        .HasColumnType("integer");

                    b.HasKey("IdTratamiento", "IdHistorialClinico");

                    b.HasIndex("HistoriaClinicaIdHistorialClinico");

                    b.HasIndex("TratamientoIdTratamiento");

                    b.ToTable("HCTratamientos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HistoriaClinica", b =>
                {
                    b.Property<int>("IdHistorialClinico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialClinico"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("AntecedentesFamiliares")
                        .HasColumnType("text");

                    b.Property<string>("AntecedentesPersonales")
                        .HasColumnType("text");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("TipoPaciente")
                        .HasColumnType("integer");

                    b.HasKey("IdHistorialClinico");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Calle")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("IdPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PacienteCobertura", b =>
                {
                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("IdCobertura")
                        .HasColumnType("integer");

                    b.Property<int>("CoberturaIdCobertura")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroAfiliado")
                        .HasColumnType("text");

                    b.Property<int>("PacienteIdPaciente")
                        .HasColumnType("integer");

                    b.HasKey("IdPaciente", "IdCobertura");

                    b.HasIndex("CoberturaIdCobertura");

                    b.HasIndex("PacienteIdPaciente");

                    b.ToTable("PacienteCoberturas");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PacienteTratamiento", b =>
                {
                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("IdTratamiento")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PacienteIdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("TratamientoIdTratamiento")
                        .HasColumnType("integer");

                    b.HasKey("IdPaciente", "IdTratamiento");

                    b.HasIndex("PacienteIdPaciente");

                    b.HasIndex("TratamientoIdTratamiento");

                    b.ToTable("PacienteTratamientos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PaseDiario", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .HasColumnType("integer");

                    b.Property<int>("IdTurno")
                        .HasColumnType("integer");

                    b.Property<int>("IdFichaSeguimiento")
                        .HasColumnType("integer");

                    b.Property<int>("FichaDeSeguimientoIdFichaSeguimiento")
                        .HasColumnType("integer");

                    b.Property<string>("FrecuenciaTurno")
                        .HasColumnType("text");

                    b.Property<int>("TratamientoIdTratamiento")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoIdTurno")
                        .HasColumnType("integer");

                    b.HasKey("IdTratamiento", "IdTurno", "IdFichaSeguimiento");

                    b.HasIndex("FichaDeSeguimientoIdFichaSeguimiento");

                    b.HasIndex("TratamientoIdTratamiento");

                    b.HasIndex("TurnoIdTurno");

                    b.ToTable("PasesDiarios");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Profesional", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Especialidad")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.ProfesionalPaciente", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteIdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("ProfesionalIdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdPaciente");

                    b.HasIndex("PacienteIdPaciente");

                    b.HasIndex("ProfesionalIdUsuario");

                    b.ToTable("ProfesionalPacientes");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.ProfesionalTurno", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdTurno")
                        .HasColumnType("integer");

                    b.Property<int>("ProfesionalIdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoIdTurno")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdTurno");

                    b.HasIndex("ProfesionalIdUsuario");

                    b.HasIndex("TurnoIdTurno");

                    b.ToTable("ProfesionalTurnos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTratamiento"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("TipoTratamiento")
                        .HasColumnType("integer");

                    b.HasKey("IdTratamiento");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTurno"));

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FichaDeSeguimientoID")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("IdTurno");

                    b.HasIndex("FichaDeSeguimientoID");

                    b.HasIndex("PacienteId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Tutor", b =>
                {
                    b.Property<int>("DNI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DNI"));

                    b.Property<string>("NumeroCompleto")
                        .HasColumnType("text");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("DNI");

                    b.ToTable("Tutor");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.TutorResponsablePaciente", b =>
                {
                    b.Property<int>("DNITutor")
                        .HasColumnType("integer");

                    b.Property<int>("DNIPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteIdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("TutorDNI")
                        .HasColumnType("integer");

                    b.HasKey("DNITutor", "DNIPaciente");

                    b.HasIndex("PacienteIdPaciente");

                    b.HasIndex("TutorDNI");

                    b.ToTable("TutorResponsables");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Documento", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", "FichaSeguimiento")
                        .WithMany("Documentos")
                        .HasForeignKey("FichaSeguimientoIdFichaSeguimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaSeguimiento");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Fichas")
                        .HasForeignKey("HistoriaClinicaIdHistorialClinico");

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalIdUsuario");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HCTratamiento", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("HCTratamientos")
                        .HasForeignKey("HistoriaClinicaIdHistorialClinico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Tratamiento", "Tratamiento")
                        .WithMany("HCTratamientos")
                        .HasForeignKey("TratamientoIdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HistoriaClinica", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithOne("HistoriaClinica")
                        .HasForeignKey("ClinicPass.DataAccessLayer.Models.HistoriaClinica", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PacienteCobertura", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.CoberturaMedica", "Cobertura")
                        .WithMany()
                        .HasForeignKey("CoberturaIdCobertura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithMany("PacienteCoberturas")
                        .HasForeignKey("PacienteIdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobertura");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PacienteTratamiento", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithMany("PacienteTratamientos")
                        .HasForeignKey("PacienteIdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Tratamiento", "Tratamiento")
                        .WithMany("PacienteTratamientos")
                        .HasForeignKey("TratamientoIdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PaseDiario", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", "FichaDeSeguimiento")
                        .WithMany("PasesDiarios")
                        .HasForeignKey("FichaDeSeguimientoIdFichaSeguimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoIdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Turno", "Turno")
                        .WithMany("PasesDiarios")
                        .HasForeignKey("TurnoIdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaDeSeguimiento");

                    b.Navigation("Tratamiento");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.ProfesionalPaciente", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithMany("ProfesionalesVinculados")
                        .HasForeignKey("PacienteIdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", "Profesional")
                        .WithMany("ProfesionalPacientes")
                        .HasForeignKey("ProfesionalIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.ProfesionalTurno", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", "Profesional")
                        .WithMany("ProfesionalTurnos")
                        .HasForeignKey("ProfesionalIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Turno", "Turno")
                        .WithMany("ProfesionalTurnos")
                        .HasForeignKey("TurnoIdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesional");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Turno", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", "FichaDeSeguimiento")
                        .WithMany()
                        .HasForeignKey("FichaDeSeguimientoID");

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaDeSeguimiento");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.TutorResponsablePaciente", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithMany("TutoresResponsables")
                        .HasForeignKey("PacienteIdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Tutor", "Tutor")
                        .WithMany("Pacientes")
                        .HasForeignKey("TutorDNI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("PasesDiarios");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HistoriaClinica", b =>
                {
                    b.Navigation("Fichas");

                    b.Navigation("HCTratamientos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Paciente", b =>
                {
                    b.Navigation("HistoriaClinica");

                    b.Navigation("PacienteCoberturas");

                    b.Navigation("PacienteTratamientos");

                    b.Navigation("ProfesionalesVinculados");

                    b.Navigation("Turnos");

                    b.Navigation("TutoresResponsables");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Profesional", b =>
                {
                    b.Navigation("ProfesionalPacientes");

                    b.Navigation("ProfesionalTurnos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Tratamiento", b =>
                {
                    b.Navigation("HCTratamientos");

                    b.Navigation("PacienteTratamientos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Turno", b =>
                {
                    b.Navigation("PasesDiarios");

                    b.Navigation("ProfesionalTurnos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Tutor", b =>
                {
                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
