// <auto-generated />
using System;
using ClinicPass.DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicPass.DataAccessLayer.Migrations
{
    [DbContext(typeof(ClinicPassContext))]
    [Migration("20251217153942_RefactorTratamientoSimple")]
    partial class RefactorTratamientoSimple
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.CoberturaMedica", b =>
                {
                    b.Property<int>("IdCobertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCobertura"));

                    b.Property<string>("NombreCobertura")
                        .HasColumnType("text");

                    b.Property<string>("TipoCobertura")
                        .HasColumnType("text");

                    b.HasKey("IdCobertura");

                    b.ToTable("CoberturasMedicas");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumento"));

                    b.Property<int>("IdFichaSeguimiento")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Ruta")
                        .HasColumnType("text");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdFichaSeguimiento");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", b =>
                {
                    b.Property<int>("IdFichaSeguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFichaSeguimiento"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdHistorialClinico")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("integer");

                    b.HasKey("IdFichaSeguimiento");

                    b.HasIndex("IdHistorialClinico");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TratamientoId");

                    b.ToTable("FichasDeSeguimiento");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HistoriaClinica", b =>
                {
                    b.Property<int>("IdHistorialClinico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialClinico"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("AntecedentesFamiliares")
                        .HasColumnType("text");

                    b.Property<string>("AntecedentesPersonales")
                        .HasColumnType("text");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.HasKey("IdHistorialClinico");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HistorialClinicoTratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .HasColumnType("integer");

                    b.Property<int>("IdHistorialClinico")
                        .HasColumnType("integer");

                    b.Property<int>("TratamientoIdTratamiento")
                        .HasColumnType("integer");

                    b.HasKey("IdTratamiento", "IdHistorialClinico");

                    b.HasIndex("IdHistorialClinico");

                    b.HasIndex("TratamientoIdTratamiento");

                    b.ToTable("HistorialClinicoTratamientos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Calle")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("IdPaciente");

                    b.ToTable("Pacientes", t =>
                        {
                            t.HasCheckConstraint("CHK_Paciente_Dni_NumericAndLength", "LENGTH(\"Dni\") BETWEEN 7 AND 8 AND \"Dni\" ~ '^[0-9]+$'");

                            t.HasCheckConstraint("CHK_Paciente_FechaNacimiento_PastDate", "\"FechaNacimiento\"<NOW()");
                        });
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PacienteCobertura", b =>
                {
                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("IdCobertura")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroAfiliado")
                        .HasColumnType("text");

                    b.HasKey("IdPaciente", "IdCobertura");

                    b.HasIndex("IdCobertura");

                    b.ToTable("PacienteCoberturas");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PaseDiario", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .HasColumnType("integer");

                    b.Property<int>("IdTurno")
                        .HasColumnType("integer");

                    b.Property<string>("FrecuenciaTurno")
                        .HasColumnType("text");

                    b.Property<int>("TratamientoIdTratamiento")
                        .HasColumnType("integer");

                    b.HasKey("IdTratamiento", "IdTurno");

                    b.HasIndex("IdTurno");

                    b.HasIndex("TratamientoIdTratamiento");

                    b.ToTable("Pases");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Profesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Especialidad")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Profesional_Dni_NumericAndLength", "LENGTH(\"Dni\") BETWEEN 7 AND 8 AND \"Dni\" ~ '^[0-9]+$'");
                        });
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.ProfesionalPaciente", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdPaciente");

                    b.HasIndex("IdPaciente");

                    b.ToTable("ProfesionalPacientes");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTratamiento"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTratamiento");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTurno"));

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdFichaSeguimiento")
                        .HasColumnType("integer");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdFichaSeguimiento");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Tutor", b =>
                {
                    b.Property<int>("DNI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DNI"));

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("text");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("DNI");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.TutorResponsablePaciente", b =>
                {
                    b.Property<int>("DNITutor")
                        .HasColumnType("integer");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.HasKey("DNITutor", "IdPaciente");

                    b.HasIndex("IdPaciente");

                    b.ToTable("TutorResponsables");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Documento", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", "FichaSeguimiento")
                        .WithMany("Documentos")
                        .HasForeignKey("IdFichaSeguimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaSeguimiento");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Fichas")
                        .HasForeignKey("IdHistorialClinico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", "Profesional")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoId");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Profesional");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HistoriaClinica", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithOne("HistoriaClinica")
                        .HasForeignKey("ClinicPass.DataAccessLayer.Models.HistoriaClinica", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HistorialClinicoTratamiento", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Tratamientos")
                        .HasForeignKey("IdHistorialClinico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Tratamiento", "Tratamiento")
                        .WithMany("Historiales")
                        .HasForeignKey("TratamientoIdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PacienteCobertura", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.CoberturaMedica", "Cobertura")
                        .WithMany("PacienteCoberturas")
                        .HasForeignKey("IdCobertura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithMany("PacienteCoberturas")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobertura");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.PaseDiario", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Turno", "Turno")
                        .WithMany("Pases")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoIdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamiento");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.ProfesionalPaciente", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithMany("ProfesionalesVinculados")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", "Profesional")
                        .WithMany("ProfesionalPacientes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Turno", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", "FichaDeSeguimiento")
                        .WithMany("Turnos")
                        .HasForeignKey("IdFichaSeguimiento");

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaDeSeguimiento");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.TutorResponsablePaciente", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Tutor", "Tutor")
                        .WithMany("Pacientes")
                        .HasForeignKey("DNITutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Paciente", "Paciente")
                        .WithMany("TutoresResponsables")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ClinicPass.DataAccessLayer.Models.Profesional", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.CoberturaMedica", b =>
                {
                    b.Navigation("PacienteCoberturas");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.FichaDeSeguimiento", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.HistoriaClinica", b =>
                {
                    b.Navigation("Fichas");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Paciente", b =>
                {
                    b.Navigation("HistoriaClinica");

                    b.Navigation("PacienteCoberturas");

                    b.Navigation("ProfesionalesVinculados");

                    b.Navigation("Turnos");

                    b.Navigation("TutoresResponsables");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Profesional", b =>
                {
                    b.Navigation("ProfesionalPacientes");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Tratamiento", b =>
                {
                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Turno", b =>
                {
                    b.Navigation("Pases");
                });

            modelBuilder.Entity("ClinicPass.DataAccessLayer.Models.Tutor", b =>
                {
                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
